# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matinv <- function(x) {
    .Call(`_bayesRCM_matinv`, x)
}

matsolve <- function(x, y) {
    .Call(`_bayesRCM_matsolve`, x, y)
}

matprod <- function(x, y) {
    .Call(`_bayesRCM_matprod`, x, y)
}

matABA <- function(x, y) {
    .Call(`_bayesRCM_matABA`, x, y)
}

matABinvA <- function(x, y) {
    .Call(`_bayesRCM_matABinvA`, x, y)
}

mattr <- function(x) {
    .Call(`_bayesRCM_mattr`, x)
}

matdet <- function(x) {
    .Call(`_bayesRCM_matdet`, x)
}

matchol <- function(x) {
    .Call(`_bayesRCM_matchol`, x)
}

log_multi_gamma <- function(p, n) {
    .Call(`_bayesRCM_log_multi_gamma`, p, n)
}

log_iwishart_InvA_const <- function(df, S) {
    .Call(`_bayesRCM_log_iwishart_InvA_const`, df, S)
}

log_J <- function(h, B, a11) {
    .Call(`_bayesRCM_log_J`, h, B, a11)
}

log_H <- function(nu, V, Omega, i, j) {
    .Call(`_bayesRCM_log_H`, nu, V, Omega, i, j)
}

log_dWish <- function(Omega, df, S) {
    .Call(`_bayesRCM_log_dWish`, Omega, df, S)
}

log_GWish_NOij_pdf <- function(b, D, Omega, i, j, edgeij) {
    .Call(`_bayesRCM_log_GWish_NOij_pdf`, b, D, Omega, i, j, edgeij)
}

